import type { Location } from '@/lib/types';

const WORK_LOCATION: Location = {
	id: 'work',
	label: 'Work',
	icon: 'images/icons/work.svg',
	kind: 'folder',
	children: [
		// ▶ Project 1
		{
			id: 'work-1',
			label: 'Vue Applications',
			icon: 'images/app-icons/folder.png',
			kind: 'folder',
			imgSrc: '',
			position: 'top-10 left-5', // icon position inside Finder
			windowPosition: 'top-[5vh] left-5', // optional: Finder window position
			children: [
				{
					id: 'work-1-1',
					label: 'Netflix Portfolio',
					icon: 'images/app-icons/folder.png',
					kind: 'folder',
					position: 'top-5 left-10',
					imgSrc: '',
					children: [
						{
							id: 'work-1-1-1',
							label: 'README.md',
							fileType: 'txt',
							description: [
								'Nuxt Portfolio Webapp that utilizes SSR, with a theme based on Netflix.',
								'Tools: \'Nuxt\', \'Vue@3\', \'Vercel\', \'Turso\', \'Tailwindcss\', \'SQLite\', \'Drizzle\', \'DaisyUi\', \'Pinia\'',
								'StartDate: September 2025',
							],
							icon: 'images/app-icons/txt.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-10 left-0',
						},
						{
							id: 'work-1-1-2',
							label: 'Website',
							fileType: 'url',
							href: 'https://losovoj-portfolio.vercel.app/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-20 left-60',
						},
						{
							id: 'work-1-1-3',
							label: 'Github',
							fileType: 'url',
							href: 'https://github.com/Lone-DO/project-netflix',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-60 left-0',
						},
					],
				},
				{
					id: 'work-1-2',
					label: 'Travel Dashboard Webapp',
					icon: 'images/app-icons/folder.png',
					kind: 'folder',
					position: 'top-35 left-10',
					imgSrc: '',
					children: [
						{
							id: 'work-1-2-1',
							label: 'README.md',
							fileType: 'txt',
							description: [
								'Digital Passport Application built using Nuxt, TypeScript, and tailwindcss for the frontend, and Drizzle + SQLite for the backend.',
								'Tools: \'Nuxt\', \'Vue@3\', \'Vercel\', \'Turso\', \'Tailwindcss\', \'SQLite\', \'Drizzle\', \'DaisyUi\', \'Pinia\'',
								'StartDate: August 2025',
								'EndDate: September 2025',
							],
							icon: 'images/app-icons/txt.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-10 left-0',
						},
						{
							id: 'work-1-1-2',
							label: 'Website',
							fileType: 'url',
							href: 'https://reisen-dashboard.vercel.app/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-20 left-60',
						},
						{
							id: 'work-1-1-3',
							label: 'Github',
							fileType: 'url',
							href: 'https://github.com/Lone-DO/project-nuxt-passport',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-60 left-0',
						},
					],
				},
				{
					id: 'work-1-3',
					label: 'Vögel - Web Book',
					icon: 'images/app-icons/folder.png',
					kind: 'folder',
					position: 'top-35 left-60',
					imgSrc: '',
					children: [
						{
							id: 'work-1-3-1',
							label: 'README.md',
							fileType: 'txt',
							description: [
								'Creative application based on the kinderbücher series \'Vögel\' in Germany',
								'Tools: \'Vue@3\', \'SASS\', \'Github Pages\'',
								'StartDate: August 2025',
								'EndDate: September 2025',
							],
							icon: 'images/app-icons/txt.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-10 left-0',
						},
						{
							id: 'work-1-3-2',
							label: 'Website',
							fileType: 'url',
							href: 'https://lone-do.github.io/project-vogel/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-20 left-60',
						},
						{
							id: 'work-1-3-3',
							label: 'Github',
							fileType: 'url',
							href: 'https://github.com/Lone-DO/project-vogel',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-60 left-0',
						},
					],
				},
				{
					id: 'work-1-4',
					label: 'Zenless Zone Zero',
					icon: 'images/app-icons/folder.png',
					kind: 'folder',
					position: 'top-5 left-60',
					imgSrc: '',
					children: [
						{
							id: 'work-1-4-1',
							label: 'README.md',
							fileType: 'txt',
							description: [
								'Creative application based on the kinderbücher series \'Vögel\' in Germany',
								'Tools: \'Vue@3\', \'SASS\', \'Github Pages\'',
								'StartDate: August 2025',
								'EndDate: September 2025',
							],
							icon: 'images/app-icons/txt.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-10 left-0',
						},
						{
							id: 'work-1-4-2',
							label: 'Website',
							fileType: 'url',
							href: 'https://lone-do.github.io/project-vogel/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-20 left-60',
						},
						{
							id: 'work-1-4-3',
							label: 'Github',
							fileType: 'url',
							href: 'https://github.com/Lone-DO/project-vogel',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-60 left-0',
						},
					],
				},
			],
		},

		// ▶ Project 2

		{
			id: 'work-2',
			label: 'Angular.js Applications',
			icon: 'images/app-icons/folder.png',
			kind: 'folder',
			imgSrc: '',
			position: 'top-30 left-45', // icon position inside Finder
			windowPosition: 'top-[5vh] left-5', // optional: Finder window position
			children: [
				{
					id: 'work-2-1',
					label: 'Ecommerce Application',
					icon: 'images/app-icons/folder.png',
					kind: 'folder',
					position: 'top-5 left-10',
					imgSrc: '',
					children: [
						{
							id: 'work-2-1-1',
							label: 'README.md',
							fileType: 'txt',
							description: [
								'Angular Ecommerce WebApp, Utilizing FakeAPI',
								'Tools: \'Angular@13.3.3\', \'SASS\'',
								'StartDate: August 2025',
								'EndDate: August 2025',
							],
							icon: 'images/app-icons/txt.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-10 left-0',
						},
						{
							id: 'work-2-1-2',
							label: 'Website',
							fileType: 'url',
							href: 'https://lone-do.github.io/ecommerce-angular/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-20 left-60',
						},
						{
							id: 'work-2-1-3',
							label: 'Github',
							fileType: 'url',
							href: 'https://github.com/lone-do/ecommerce-angular',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-60 left-0',
						},
					],
				},
				{
					id: 'work-2-2',
					label: 'TODO Application',
					icon: 'images/app-icons/folder.png',
					kind: 'folder',
					position: 'top-45 left-10',
					imgSrc: '',
					children: [
						{
							id: 'work-2-2-1',
							label: 'README.md',
							fileType: 'txt',
							description: [
								'Basic Angular@20.1 Application for learning how the basics of how this framework ticks.',
								'Tools: \'Angular@20.0\', \'Github Pages\', \'Figma\'',
								'StartDate: July 2025',
								'EndDate: July 2025',
							],
							icon: 'images/app-icons/txt.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-10 left-0',
						},
						{
							id: 'work-2-2-2',
							label: 'Website',
							fileType: 'url',
							href: 'https://lone-do.github.io/todo-angular/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-20 left-60',
						},
						{
							id: 'work-2-2-3',
							label: 'Github',
							fileType: 'url',
							href: 'https://github.com/Lone-DO/todo-angular',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-60 left-0',
						},
					],
				},
			],
		},

		// ▶ Project 3
		{
			id: 'work-3',
			label: 'React.js Applications',
			icon: 'images/app-icons/folder.png',
			kind: 'folder',
			imgSrc: '',
			position: 'top-60 left-5', // icon position inside Finder
			windowPosition: 'top-[5vh] left-5', // optional: Finder window position
			children: [
				{
					id: 'work-3-1',
					label: 'Animal Crossing: Radio',
					icon: 'images/app-icons/folder.png',
					kind: 'folder',
					position: 'top-5 left-10',
					imgSrc: '',
					children: [
						{
							id: 'work-3-1-1',
							label: 'README.md',
							fileType: 'txt',
							description: [
								'Creative application that brings the daily soundtracks of Animal Crossing back.',
								'Able to choose smoothly between the user\'s desired Generation,',
								'from the hit classics like original Animal Crossing from GameCube,',
								'to City Folk from the WII U, and the latest New Leaf on the 3DS.',
								'Built with the MERN stack, the backend API utilizes MongoDB as its database.',
								'Tools: \'MERN Stack\', \'Mongo\', \'Express\', \'Ember.js\', \'Node.js\', \'SASS\', \'jQuery\', \'HTML5\', \'CSS3\', \'JavaScript\', \'React.js\'',
								'StartDate: October 2019',
								'EndDate: December 2019',
							],
							icon: 'images/app-icons/txt.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-10 left-0',
						},
						{
							id: 'work-3-1-2',
							label: 'Website',
							fileType: 'url',
							href: 'https://lone-do.github.io/project-ac/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-20 left-60',
						},
						{
							id: 'work-3-1-3',
							label: 'Github',
							fileType: 'url',
							href: 'https://github.com/lone-do/project-ac/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-60 left-0',
						},
					],
				},
				{
					id: 'work-3-2',
					label: '2019 Portfolio',
					icon: 'images/app-icons/folder.png',
					kind: 'folder',
					position: 'top-45 left-10',
					imgSrc: '',
					children: [
						{
							id: 'work-3-2-1',
							label: 'README.md',
							fileType: 'txt',
							description: 'Original Portfolio Website',
							icon: 'images/app-icons/txt.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-10 left-0',
						},
						{
							id: 'work-3-2-2',
							label: 'Website',
							fileType: 'url',
							href: 'https://lone-do.github.io/2019-portfolio/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-20 left-60',
						},
						{
							id: 'work-3-2-3',
							label: 'Github',
							fileType: 'url',
							href: 'https://github.com/lone-do/2019-portfolio/',
							icon: 'images/app-icons/safari.png',
							kind: 'file',
							imgSrc: '',
							position: 'top-60 left-0',
						},
					],
				},
			],
		},
	],
};

const ABOUT_LOCATION: Location = {
	id: 'about',
	label: 'About me',
	icon: 'images/icons/info.svg',
	kind: 'folder',
	children: [
		{
			id: 'about-1',
			label: 'me.png',
			icon: 'images/app-icons/image.png',
			kind: 'file',
			fileType: 'img',
			position: 'top-10 left-5',
			imgSrc: 'images/me/code-lou-me.JPG',
		},
		{
			id: 'about-2',
			label: 'casual-me.png',
			icon: 'images/app-icons/image.png',
			kind: 'file',
			fileType: 'img',
			position: 'top-38 left-40',
			imgSrc: 'images/me/casual-me.JPG',
		},
		{
			id: 'about-3',
			label: 'conference-me.png',
			icon: 'images/app-icons/image.png',
			kind: 'file',
			fileType: 'img',
			position: 'top-82 left-40',
			imgSrc: 'images/me/conference-me.jpeg',
		},
		{
			id: 'about-4',
			label: 'about-me.txt',
			icon: 'images/app-icons/txt.png',
			kind: 'file',
			fileType: 'txt',
			position: 'top-60 left-5',
			subtitle: 'Meet the Developer Behind the Code',
			imgSrc: 'images/me/leon.jpg',
			description: [
				'Hey! I’m Shawn 👋, a software engineer who enjoys building beautiful, interactive applications, & solving challenging problems.',
				'I specialize in Frontend development, Nuxt.js, and system-design/architecture.',
				'I’m enjoy mentoring, testing, writing code with a strong foundation based on best practices, and more testing',
				'Outside of dev work, you\'ll find me tweaking with gadgets, video games, or leveling up as a father.',
			],
		},
		{
			id: 'about-5',
			label: 'Blog: Developer Advocacy',
			icon: 'images/app-icons/safari.png',
			kind: 'file',
			fileType: 'url',
			position: 'top-10 left-80',
			imgSrc: '',
			href: 'https://www.kentuckianaworks.org/news/codelou-2022',
		},
	],
};

const RESUME_LOCATION: Location = {
	id: 'resume',
	label: 'Resume',
	icon: 'images/icons/file.svg',
	kind: 'folder',
	children: [
		{
			id: 'resume-1',
			label: 'Resume.pdf',
			imgSrc: '',
			icon: 'images/app-icons/pdf.png',
			kind: 'file',
			fileType: 'pdf',
			// you can add `href` if you want to open a hosted resume
			// href: '/files/resume.pdf',
		},
	],
};

const TRASH_LOCATION: Location = {
	id: 'trash',
	label: 'Trash',
	icon: 'images/icons/trash.svg',
	kind: 'folder',
	children: [
		{
			id: 'trash-1',
			label: 'skong.webp',
			icon: 'images/app-icons/image.png',
			kind: 'file',
			fileType: 'img',
			position: 'top-10 left-10',
			imgSrc: 'images/trash/skong.webp',
		},
		{
			id: 'trash-2',
			label: 'trash.png',
			icon: 'images/app-icons/image.png',
			kind: 'file',
			fileType: 'img',
			position: 'top-40 left-10',
			imgSrc: 'images/trash/gnomed.webp',
		},
		{
			id: 'trash-3',
			label: 'magic.gif',
			icon: 'images/app-icons/image.png',
			kind: 'file',
			fileType: 'img',
			position: 'top-40 left-80',
			imgSrc: 'images/trash/slownet.gif',
		},
	],
};

export const FINDER_LOCATIONS = {
	work: WORK_LOCATION,
	about: ABOUT_LOCATION,
	resume: RESUME_LOCATION,
	trash: TRASH_LOCATION,
};
